name: install

on: page_build

jobs:
  build:
    if: github.repository == 'Blaok/tapa'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Install from script
        run: ./install.sh
