name: lint

on:
  - push
  - pull_request

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout myself
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          curl --location --output /tmp/clang-format \
            https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-208096c1/clang-format-14_linux-amd64
          sudo install /tmp/clang-format /usr/local/bin/clang-format
          rm /tmp/clang-format
          clang-format --version

          python3 -m pip install \
            isort==5.10.1 \
            yapf==0.32.0 \

          isort --version
          yapf --version

          curl --location --output /tmp/shfmt \
            https://github.com/mvdan/sh/releases/download/v3.5.1/shfmt_v3.5.1_linux_amd64
          sudo install /tmp/shfmt /usr/local/bin/shfmt
          rm /tmp/shfmt
          shfmt --version

          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            iverilog \
            moreutils \

      - name: Check format
        run: |
          ./format.sh
          git diff --color --exit-code
      - name: Lint
        run: .github/scripts/lint.sh
